### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by YvanYifeiLi** [tomy0000000/Coon#5] opened 2019-12-26 23:09 UTC
Hello there, 

Please tell me why this error happens. I've set up app id successfully.

<img width="605" alt="Image Copied on 2019-12-26 at 17 08 32 PM" src="https://user-images.githubusercontent.com/32441766/71493156-5dfb0900-2802-11ea-8a45-d09b9c31fcf2.png">

**Comment by tomy0000000** [comment] 2019-12-27 09:09
This is likely a duplicate of #1 
Please make sure you've updated to the latest version.
(Currently 1.1.0)
Also, as your screenshot indicate,
your alfred is also an legacy version,
try updating to the latest version to prevent anything else went wrong.

**Comment by YvanYifeiLi** [comment] 2019-12-27 14:54
Thanks for the reply, but it fails.

I've updated to the last versions of both Alfred and this workflow (you can check by the version number in the screenshot). It failed as usual and showed below.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/32441766/71521395-39e10b80-2886-11ea-938f-e0a5406d1096.png">

And I'm pretty sure the app id works, as below.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/32441766/71521465-8cbac300-2886-11ea-8964-fae5e5edca6e.png">

**Comment by tomy0000000** [comment] 2019-12-30 11:25
"favorites" is actually a "Settings" item instead of "Config".
It's a JSON file located in your user library folder,
for more comprehensive description, see [here](https://github.com/tomy0000000/Coon#config--settings)

Normally, Coon should create this JSON Settings file upon your installation.
A default setting JSON file should look like the following:
```json
{
  "__workflow_last_version": "1.1.0", 
  "favorites": [
    "EUR", 
    "CNY", 
    "JPY", 
    "GBP"
  ]
}
```

But incase anything went wrong,
you can always delete the file,
Coon will then create a new one for you.

Try manually delete the file,
and see if that fix the problem.

If not, please kindly provide your setting file,
along with the debug information,
so I can dive into the problem and see what I can do.

To retrieve debug information.
tap the 🕷 in Alfred as follow,
and type query, logs will be generated at the bottom.
<img width="913" alt="snapshots 2019-12-30 下午7 21 40" src="https://user-images.githubusercontent.com/23290356/71580049-0928fc80-2b3a-11ea-8a73-15d6585331ab.png">

**Comment by YvanYifeiLi** [comment] 2019-12-30 15:25
Thank you! It's solved!

I've opened the settting.json and paste the default setting script provided by you.

The original one looks like this:

'''
{
  "__workflow_last_version": "1.1.0",
}
'''

**Comment by tomy0000000** [comment] 2019-12-31 07:23
Glad to know it's fixed ;-)

**Closed by tomy0000000** 2019-12-31 07:23 UTC
